apiVersion: v1
data:
  config.yml: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/docker/registry/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
kind: ConfigMap
metadata:
  name: config-cm
  namespace: registry
