apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    error
        Parsers_File parsers.conf
        Plugins_File plugins.conf
        HTTP_Server  Off
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name        forward
        Listen      0.0.0.0
        Port        24224
        Chunk_Size  32
        Buffer_Size 64

    [OUTPUT]
        Name file
        Match *
        Path /logs/
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fluent-bit-server-config
  namespace: logging
