apiVersion: v1
data:
  prometheus.yml: |+
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        #scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
            #- job_name: 'docker'
        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.
        #static_configs:
        # - targets: ['localhost:9323']
      - job_name: 'node_exporter'
        scrape_interval: 15s
        static_configs:
          - targets: ['nuc5:9100']
          - targets: ['nuc6:9100']
          - targets: ['nuc8:9100']
          - targets: ['piz:9100']
          - targets: ['pi3:9100']
          - targets: ['pi4:9100']
          - targets: ['key:9100']
            #- job_name: 'snmp'
      - job_name: 'pushgateway'
        scrape_interval: 60s
        honor_labels: true
        static_configs:
          - targets: ['nuc5:30091']
          - targets: ['nuc6:9091']
      - job_name: 'hs110'
        scrape_interval: 60s
        honor_labels: true
        static_configs:
          - targets: ['hs110-plug-57:80'] # NUC6
          - targets: ['hs110-plug-55:80'] # TS140
          - targets: ['hs110-plug-56:80'] # NUC8

        # Override the global default and scrape targets from this job every 5 seconds.
        #scrape_interval: 5s
        #static_configs:
        #  - targets:
        #    - 192.168.7.1  # SNMP device.
        #metrics_path: /snmp
        #params:
        #  module: [if_mib]
        #relabel_configs:
        #  - source_labels: [__address__]
        #    target_label: __param_target
        #  - source_labels: [__param_target]
        #    target_label: instance
        #  - target_label: __address__
        #    replacement: 127.0.0.1:9116  # SNMP exporter.

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-config-cm
  namespace: monitoring
